"""empty message

Revision ID: 37eeb23d1f61
Revises: e3fafd6a2948
Create Date: 2022-04-30 07:40:43.080728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37eeb23d1f61'
down_revision = 'e3fafd6a2948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
