"""empty message

Revision ID: e3fafd6a2948
Revises: 0b32d595c19a
Create Date: 2022-04-30 07:40:20.667014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3fafd6a2948'
down_revision = '0b32d595c19a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
